[32m2023-06-01 15:54:31 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - 81271 - LOGS_CAPTURED - Started capturing logs in process (pid: 81271).
[32m2023-06-01 15:54:31 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - 81271 - cache_properties - STEP_START - Started execution of step "cache_properties".
[32m2023-06-01 15:54:32 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - cache_properties - Loading file from: /Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/realestate-scraping/tmpaxgkad7t/storage/get_new_or_changed_props
[32m2023-06-01 15:54:32 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - 81271 - cache_properties - ASSET_OBSERVATION - DagsterEventType.ASSET_OBSERVATION for step cache_properties
[32m2023-06-01 15:54:32 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - 81271 - cache_properties - LOADED_INPUT - Loaded input "get_new_or_changed_props" using input manager "io_manager"
[32m2023-06-01 15:54:32 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - 81271 - cache_properties - STEP_INPUT - Got input "get_new_or_changed_props" of type "Any". (Type check passed).
[32m2023-06-01 15:54:32 +0200[0m - dagster - [34mINFO[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - cache_properties - {'id': '7686027', 'fingerprint': '7686027-2380000', 'city': 'meilen', 'radius': '1', 'last_normalized_price': '2380000'}
[32m2023-06-01 15:54:32 +0200[0m - dagster - [34mINFO[0m - __ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - cache_properties - 7686027
[32m2023-06-01 15:54:32 +0200[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 3533868a-d3ce-4240-a798-be40efa3c3b4 - 81271 - cache_properties - STEP_FAILURE - Execution of step "cache_properties" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "cache_properties"::

TypeError: APIHelper._get_property_from_api() got multiple values for argument 'id'

Stack Trace:
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_solid_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/realestate-scraping/realestate_scraping/assets/core/realestate_scraping.py", line 180, in cache_properties
    result = context.resources.realestate_api._get_property_from_api(id=_property['id'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/ratelimit/decorators.py", line 113, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/ratelimit/decorators.py", line 80, in wrapper
    return func(*args, **kargs)
           ^^^^^^^^^^^^^^^^^^^^
[0m
