[32m2023-04-25 20:40:19 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ba242796-23fd-4e17-880d-33ef0d0e759c - 25066 - LOGS_CAPTURED - Started capturing logs in process (pid: 25066).
[32m2023-04-25 20:40:19 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - ba242796-23fd-4e17-880d-33ef0d0e759c - 25066 - upload_to_s3 - STEP_START - Started execution of step "upload_to_s3".
[32m2023-04-25 20:40:19 +0200[0m - dagster - [34mINFO[0m - __ASSET_JOB - ba242796-23fd-4e17-880d-33ef0d0e759c - upload_to_s3 - ./realestate_scraping/data/230425_real_estate_data_zuerich_1_km_part_3.html
[32m2023-04-25 20:40:19 +0200[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - ba242796-23fd-4e17-880d-33ef0d0e759c - 25066 - upload_to_s3 - STEP_FAILURE - Execution of step "upload_to_s3" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "upload_to_s3"::

AttributeError: 'S3Credentials' object has no attribute 'bucket_name'

Stack Trace:
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 124, in _coerce_solid_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/env/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 118, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/realestate-scraping/realestate_scraping/assets/core/realestate_scraping.py", line 142, in upload_to_s3
    context.resources.s3._upload_file_to_s3(bucket, filename, _obj)
  File "/Users/ctac/Desktop/Data Engineer /Projects/realestate_scraping_project/realestate-scraping/realestate_scraping/__init__.py", line 34, in _upload_file_to_s3
    s3_client.fput_object(self.bucket_name, key, filename)
                          ^^^^^^^^^^^^^^^^
[0m
